name: Test Build

on:
  # Runs on pushes to main/master
  push:
    branches: [ main, master ]
  # Optionally, also run on pull requests to main/master
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.41.0"
          
      - name: Run Tests
        run: deno test -A
          
      - name: Test Build
        run: |
          rm -f deno.lock
          deno cache main.ts
          deno task build
